[workspace]
members = [
    "crates/*",
    "plugins/*"
]
resolver = "3"

[package]
name = "barebones"
version = "0.1.1"
edition = "2024"

[[bin]]
name = "barebones-cli"
path = "src/bin/main.rs"

[workspace.dependencies]
cli-dev = { path = "crates/cli-dev" }

abi_stable = "0.11.3"
clap = { version = "4", features = ["derive"]}
comfy-table = "7"
config = { version = "0.15", features = ["toml"] }
crossbeam-channel = "0.5"
csv = "1"
ctrlc = "3"
dirs = "6"
exitcode = "1"
log = "0.4"
notify = "8"
thiserror = "2"
toml = "0.9.8"
self_update = { version = "0.42",  default-features = false, features = ["rustls", "archive-tar", "compression-flate2",] }
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"


[dependencies]
cli-dev.workspace = true

abi_stable.workspace = true
anyhow = "1" # Executable dependency only
chrono = "0.4"
clap.workspace = true
config.workspace = true
crossbeam-channel.workspace = true
ctrlc.workspace = true
dirs.workspace = true
exitcode.workspace = true
human-panic = "2" # Only executable should handle panic
notify.workspace = true
self_update.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber = "0.3" # This should not be responsibility of any crate

[dev-dependencies]
assert_cmd = "2"
trycmd = "0.15"

[lints]
workspace = true

[workspace.lints.clippy]
all = "deny"
wildcard_imports = "deny"
missing_const_for_fn = "deny"
option_if_let_else = "deny"
or_fun_call = "deny"
get_first = "deny"
redundant_clone = "deny"
manual_ok_or = "deny"
unnecessary_wraps = "deny"
needless_collect = "deny"
get_unwrap = "deny"
manual_while_let_some = "deny"
panicking_unwrap = "deny"
unnecessary_unwrap = "deny"
unnecessary_literal_unwrap = "deny"
unwrap_in_result = "deny"

[workspace.lints.rust]
nonstandard-style = "deny"
future-incompatible = "deny"
non_local_definitions = "allow"
