name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Format
      run: cargo fmt -- --check
  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install stable@stable toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - uses: Swatinem/rust-cache@v2
    - name: Run Clippy
      run: cargo clippy --locked --all-features --all-targets
      
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo check --locked
      
  test:
    name: Tests
    strategy:
      matrix:
        runner: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Test
        run: | 
          mkdir -p ~/.barebones/
          cp ./config.toml ~/.barebones/config.toml
          cargo build -r -p greeter
          cp ./target/release/*greeter* ~/.barebones/
          cargo test --all --locked
